#!/bin/bash

echo "📋 Mikrotik SNMP Setup Checklist"
echo "================================="
echo ""
echo "✅ CORE-BGP (103.144.46.219) - SNMP Enabled"
echo ""
echo "❌ Need to configure SNMP on other devices:"
echo "   • 10.10.10.1"
echo "   • 172.16.1.1" 
echo "   • 103.144.46.1"
echo "   • 103.144.46.18"
echo ""
echo "================================="
echo "📝 Commands to run on EACH Mikrotik:"
echo ""
echo "/snmp set enabled=yes"
echo "/snmp community add name=xxkenxyz addresses=0.0.0.0/0"
echo ""
echo "================================="
echo "🔍 To verify SNMP is working:"
echo ""
echo "On Ubuntu:"
echo "   cd /root/Grafana-Mikrotik"
echo "   bash test-core.sh"
echo ""
echo "On Mikrotik:"
echo "   /tool snmp-get address=127.0.0.1 oid=.1.3.6.1.2.1.1.1.0"
echo ""
echo "================================="
echo "🔥 If still not showing in Grafana:"
echo ""
echo "1. Check Prometheus targets:"
echo "   curl http://localhost:9090/api/v1/targets"
echo ""
echo "2. Restart SNMP exporter:"
echo "   docker-compose restart snmp_exporter"
echo ""
echo "3. Check logs:"
echo "   docker-compose logs snmp_exporter"
echo ""
echo "4. Force Prometheus reload:"
echo "   docker-compose restart prometheus"
